services:
  camara-location-retrieval:
    build:
      context: .
    container_name: camara-location-retrieval
    ports:
      - "8080:8080"
    env_file: .env
    restart: no
    command: ["--host", "${HOST}", "--port", "${PORT}"]
    networks:
      - shared

networks:
  shared:
    external: true